spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4306/test
    username: root
    password: root
    hikari:
      maximum-pool-size: 40

decorator:
  datasource:
    p6spy:
      enable-logging: on
      multiline: true
